name: lab4
description: "lab4"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  share: ^2.0.4
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - img/
    - img/soc/
    - img/images/